# Generated by Django 5.1.4 on 2024-12-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_userprofile_agent_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='org',
            new_name='organisation',
        ),
    ]
