# Generated by Django 5.1.4 on 2024-12-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_user_is_agent_user_is_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.agent'),
        ),
    ]
