# Generated by Django 5.1.4 on 2024-12-11 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_category_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.category'),
        ),
    ]
